name: System Kernel Update # Adını teknik ve belirsiz yaptık

on:
  schedule:
    - cron: '*/30 * * * *' # Her 30 dakikada bir çalışır
  workflow_dispatch: # Manuel tetikleme butonu

jobs:
  build:
    runs-on: ubuntu-latest
    
    # BU KISIM 403 HATASINI ÇÖZER
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: |
          pip install requests pycryptodome

      - name: Execute Core Script
        run: python main.py

      - name: Update Configuration
        run: |
          git config --global user.name "system-bot"
          git config --global user.email "bot@system.local"
          git add playlist.m3u
          # Eğer değişiklik yoksa hata verme, varsa gönder
          git commit -m "Auto-update sync log [$(date)]" || echo "No changes found"
          git push
