name: System Cache Update

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  sync-process:
    runs-on: ubuntu-latest
    
    # GitHub Action Bot'a yazma izni verir (Ã–nemli!)
    permissions:
      contents: write

    steps:
      - name: Load Repository
        uses: actions/checkout@v3

      - name: Initialize Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Modules
        run: |
          pip install -r requirements.txt

      - name: Run Synchronization
        run: python main.py

      - name: Push Updates
        run: |
          git config --global user.name "sys-bot"
          git config --global user.email "bot@sys.internal"
          git add playlist.m3u
          git commit -m "Sync log update [$(date)]" || echo "No changes"
          git push
